server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  messaging:
    exchange: test-exchange
    queue: test-queue
    routing-key: test.created

  mail:
    host: localhost
    port: 1025
    username: test
    password: test
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  jackson:
    serialization:
      INDENT_OUTPUT: true

logging:
  level:
    root: WARN
