server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
    contexts: dev
  application:
    name: challenge-app
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    # Para usar Gmail debes habilitar "App passwords" o permitir "apps menos seguras".
    host: smtp.gmail.com
    port: 587
    username: tu-email@gmail.com
    password: tu-contraseña
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  messaging:
    exchange: customer-exchange
    queue: customer-queue
    routing-key: customer.created

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    url: /v3/api-docs
  packages-to-scan: org.challenge_app.controller
  show-actuator: true
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            liquibase: DEBUG
    liquibase: TRACE

